# Generated by Django 4.2.1 on 2023-06-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brotherInCode', '0005_tutores_sobre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaotutor',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
