# Generated by Django 4.2.1 on 2023-06-05 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brotherInCode', '0006_alter_avaliacaotutor_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='tutores',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='tutores',
            name='id_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.contas'),
        ),
    ]
